### PR TITLE
Align macrostate PDBs

### PR DESCRIPTION
**Pull request by maxentile**
- Aligns all structures to a single configuration sampled from the minimum free energy macrostate and saves PDBs
- Produces a plot to help assess whether the macrostate samples
  are "compact" w.r.t. RMSD

### CODE REVIEW

**Comment by jchodera** [comment]
> Aligns all structures to a single configuration sampled from the minimum free energy macrostate and saves PDBs

I think we had discussed a two-stage procedure here:
1. Align the cluster generator onto a single structure (e.g. the minimum free energy macrostate)
2. Align cluster members onto their cluster generator

**Comment by maxentile** [comment]
Ahh, right, sorry I had misinterpreted the specification, fixing now.

Note that we don't actually have structures for the cluster generators (the "generators" are points in the tICA projection that don't necessarily correspond to a structure), so I'll just say the "generator" is the configuration with the minimum mean RMSD to all other samples drawn from that macrostate?

**Comment by jchodera** [comment]
> Note that we don't actually have structures for the cluster generators (the "generators" are points in the tICA projection that don't necessarily correspond to a structure), so I'll just say the "generator" is the configuration with the minimum mean RMSD to all other samples drawn from that macrostate?

Oh, right---I keep forgetting we're using k-means and not k-medoids (which we used in the 2007 paper for exactly this reason). 

Yes, this sounds like a fine approach.

**Comment by maxentile** [comment]
I think this should be ready to review and merge: @sonyahanson , @jchodera ?

**Comment by jchodera** [comment]
Looks great!

**Pull request merged**
