### PR TITLE
Fixing a bug and adding a shell script

### PR DESCRIPTION
**Pull request by steven-albanese**
So, I found a bug where `project_name` wasn't being passed to `plot_sanity_check`, which was throwing up an error. Just wanted to merge in the fix for that. I also added `pipeline-torque.sh`, which is a shell script for running the pipeline on the batch queue on the cluster. 

There are some other small changes, like `max_iter`, which I doubled because 500 steps wasn't enough to converge clustering the WT mTOR kinase domain data, but I don't think that's necessarily a change that needs to be included here. I can revert it, if you'd like

### CODE REVIEW

**Comment by steven-albanese** [comment]
Oh- I also commented out a few lines where the script was trying to pickle some generators, which was giving me an error message as well. They don't appear to be used elsewhere at the moment, but I can revert those as well if wanted

**Comment by maxentile** [comment]
Thanks for finding and correcting these issues!

Looks good to me.

**Comment by steven-albanese** [comment]
@maxentile and I noticed a problem where using a `path_to_trajs` with a wild card would still return only a single trajectory when printing `fnames`. Seems like using single quotes around the trajectory fixes that problem

**Comment by jchodera** [comment]
Awesome! Are there any sample plots being generated with this to show what the pipeline is doing so far? If so, I'd love to see them! Maybe share them on the #msm slack channel?

**Comment by steven-albanese** [comment]
sorry @jchodera, I just saw your comment. The plots being generated here are the same as I showed you when we met earlier today. Maybe we could run the pipeline on a more straightforward case than mTOR to see? I've got it chugging away on an EGFR project over the weekend

**Comment by steven-albanese** [comment]
Ok this should be ready to merge, I think I've cleaned everything up appropriately!

**Comment by sonyahanson** [comment]
Thanks for fixing these typos, Steve. I hadn't been able to get the image making scripts to work, yet, so this is great! And yeah the pickling problem is already in issue #2. Will merge! (We can add show plots in a later PR or on Slack.)

**Pull request merged**
