### PR TITLE
fixed a typo in my branch

### PR DESCRIPTION
**Pull request by steven-albanese**
Fixing the problem reference on the msm channel on slack

### CODE REVIEW

**Comment by steven-albanese** [comment]
@sonyahanson I'm going to merge unless there's an objection!

**Comment by sonyahanson** [comment]
Does `make_figures.py` also need to be changed? https://github.com/choderalab/msm-pipeline/blob/master/make_figures.py#L21

**Comment by steven-albanese** [comment]
I'm thinking of removing `make_figures.py`, because it won't work with the way `make_plots` works, until we figure out the pickle issue

**Comment by sonyahanson** [comment]
Ahhh, okay.

**Comment by sonyahanson** [comment]
merge away, then!

**Comment by steven-albanese** [comment]
Just removed that script, it was quick to whip up if we find a need for it again, and it can be done more intelligently than I did it

**Pull request merged**
